### ISSUE TITLE
Mandatory Sequence Header in configOBUs

### ISSUE THREAD

**Issue by porcelijn** [AOMediaCodec/av1-isobmff#100]
As a follow up on issue #75, I would like to make a case for recommendation that `av1C` configOBUs MUST (or SHOULD) contain a Sequence Header so that the right decoder can be selected before having to parse the data, as argued in a Matroska/WebM thread: https://www.ietf.org/mail-archive/web/cellar/current/msg01614.html

> ...
> We have the choice of make the Sequence Header mandatory in CodecPrivate (MUST) make it highly recommended (SHOULD), just suggested (MAY) or not put it at all.
>
> IMO it should always be there. Because as stated above, if not people will likely not write it. And players will have to handle the case where it's not there.
>
> And the reason why it should be there is for playback reasons, so that the right decoder can be selected before having to parse the data. There's a reason H264/H265 have profiles, it's so that you can tell if you can decode something or not and how. In many cases you get hardware decoding and in other cases not. This will likely be the same for AV1, for example there might never be hardware decoders doing 12 bits, that doesn't mean hardware decoding should never be used.
>
> In the case of avcodec, deciding if HW is going to be used needs to be done before starting the decoder, before parsing any codec data. Because you need to chose whether 1 thread should be used (a limitation of HW decoders on Windows and Linux at least) or multiple. And you can't switch once the codec is initialized. That situation is still not too bad. If one has to use completely different code for HW decoding (like Intel's MediaSDK API) and for SW decoding (libaom) it gets worse. You'd need to parse the codec data before deciding which one to use. That also requires an extra buffering step at the beginning to probe the codec data and not lose these data (still need to be fed to the codec once it's initialized) (while the interleaved audio is going through the decoder already, especially in WebM where audio should come before video).
>
> We also have the counter example of not having the codec characteristics known in advance with VP9. Some GPU are capable of decoding 8 bits VP9 but not 10 bits. In VLC (and other apps using libavcodec) we can't decide whether to use 1 thread or many before intializing the decoder. So we use many which is the case that works best. But when the HW decoder is used it's from multiple threads which is not how it's designed to be used, has performance issues and sometimes crashes.
>
> If we make the Sequence Header OBU mandatory in the CodecPrivate we avoid all these issues on the playback side. It puts the trouble of extracting that data on the muxer/encoder side. So I think it's the right way for Matroska/WebM and also the right way for ISOBMFF, so I cc Cyril in this thread.

**Comment by jamrial** [comment]
>As a follow up on issue #75, I would like to make a case for recommendation that av1C configOBUs MUST (or SHOULD) contain a Sequence Header so that the right decoder can be selected before having to parse the data

What you mention is precisely the reason why the custom fields in av1C before configOBUs were added. So enough information to choose a decoder is always present even if no actual SH OBU is present.

**Comment by porcelijn** [comment]
I disagree. The spec defines the custom fields to reflect exactly what was already supposed to be in the configOBUs (prior to version 1) and adds nothing new. It distils _some_ information from the configOBUs -- barely more than the basic part of codec string and just enough to cover the particular matroska example, but does not address the gist of it.

It's easy to think of a similar example where dispatching between implementations is impossible given only the custom fields. Is it HDR content? Is it 4k? What if my implementation does not support use 128x128 superblocks, warped_motion or some other feature? What if another implementation needs to know about some bits upon initialization?

Unless I've completely misinterpreted the AV1 (bitstream) spec a stream must start with a Sequence Header and it would be the first thing any encoder will produce. Similarly, it would be the first thing a decoder would need - possibly in an initialization stage where the actual AV1 Sample data is not yet available. A player can't synthesize a Sequence Header OBU from av1C custom fields.

So phrased differently - if we have a sequence header, what would be the advantage of *not* including it in the init segment?

**Comment by tomfinegan** [comment]
> It's easy to think of a similar example where dispatching between implementations is impossible given only the custom fields. Is it HDR content? Is it 4k? 

This information is already carried elsewhere in ISOBMFF and other containers. A, playback, encoding or remuxing pipeline will have this information available from the input demuxer. For the encoding case it would be required as input metadata (of some sort) when handling raw image input.

> What if my implementation does not support use 128x128 superblocks, warped_motion or some other feature? 

Can you direct me to the part of the AV1 specification that specifies 128x128 superblock or warped_motion support is optional for an AV1 decoder? Could you also clarify what "some other feature" means? I believe, and correct me if I'm wrong, the only parts of the specification that are optional for AV1 decoders to support are those relating to the Tile List OBU.

> So phrased differently - if we have a sequence header, what would be the advantage of not including it in the init segment?

One example is an encoding pipeline or AV1 encoder implementation that cannot produce a Sequence Header OBU before encoding its first output sample. The advantage of the current binding specification is that fields required for a decoder to be initialized are mandatory in the init data. Using a live encoder as an example, and assuming the example live encoder cannot produce the Sequence Header OBU until the first sample is encoded, this allows the implementation to emit initialization data before encoding a sample.

**Comment by porcelijn** [comment]
> This information is already carried elsewhere in ISOBMFF and other containers.

Okay, the DRY principle makes sense in principle, though the overhead per track is modes (typically around 15 bytes per SH, 8 for metadata).

> Can you direct me to the part of the AV1 specification that specifies 128x128 superblock or warped_motion support is optional for an AV1 decoder? Could you also clarify what "some other feature" means?

:smirk: I get your point. What I was thinking of is for example a hardware decoder with a software fall-back for 128x128 superblocks. Given the custom fields (and other ISOBMFF boxes) it could only speculatively select one or the other pipelines based upon initialization unless it has the configOBUs.

> The advantage of the current binding specification is that fields required for a decoder to be initialized are mandatory in the init data.

I would say: a decoder could be _partially_ initialized at best. In your a theoretical live encoder  example, the sequence headers would have to comply with the mandatory av1C fields (or risk violating the spec), so the sub system would need to be pre-configured to the extent of those fields. But if I could inject these parts of the sequence header, why couldn't I inject all of them and then use the configOBUs to advertise that?

I think it's similar to avc1, where sps/pps are mandatory in avcC.

**Comment by tomfinegan** [comment]
I'm closing this issue, for the following reasons.

First, the original text you cited in the issue report was written before the current version of the av1C was specified. At the original time of writing, 19 July 2018, the av1C looked like this:

```
aligned (8) class AV1CodecConfigurationRecord {
  unsigned int (3) reserved = 0;
  unsigned int (1) initial_presentation_delay_present;
  if (initial_presentation_delay_present) {
    unsigned int (4) initial_presentation_delay_minus_one;
  } else {
    unsigned int (4) reserved;
  }
  unsigned int (8)[] configOBUs;
}
```

Given that version of the av1C it was certainly arguable that inclusion of the Sequence Header OBU in configOBUs should be mandatory. The addition of seq_profile, seq_level_idx_0, and seq_tier_0 (and the other fields) to av1C changed that.

This topic has already been explored in depth within the following issues and pull requests:

- Issue https://github.com/AOMediaCodec/av1-isobmff/issues/46
- PR https://github.com/AOMediaCodec/av1-isobmff/pull/47
- Issue https://github.com/AOMediaCodec/av1-isobmff/issues/50

After extended discussion the decision was made to use the currently specified av1C, and leave presence of the Sequence Header OBU in configOBUs optional. This version of the AV1 configuration has been adopted by AOM Codec WG via consensus, and I don't believe there's a strong argument here for changing it.

**Comment by porcelijn** [comment]
> This version of the AV1 configuration has been adopted by AOM Codec WG via consensus, and I don't believe there's a strong argument here for changing it.

Okay that makes sense, I suppose. Guess I should have voiced my opinion earlier but was off guard during summer holidays - the ship has sailed.

Regardless; congrats on the v1.0.0 milestone!
