### ISSUE TITLE
CENC Subsamples

### ISSUE THREAD

**Issue by jeanlf** [AOMediaCodec/av1-isobmff#105]
The spec states
"A subsample SHALL be created for each tile."

This implies that if a previous subsample is present with no encrypted data, one has to start a new subsample. Is this the intended behaviour ? This is not really optimal since it enforces a first subsample with no encrypted data whenever we have unencrypted OBUs before tile data (eg, frame header or clear metadata.
Shouldn't we rather have a new subsample for a tile only if there is something encrypted before ?

**Comment by cconcolato** [comment]
> "A subsample SHALL be created for each tile."

Note that it does not say a subsample shall be created for the clear, header part only.

> This implies that if a previous subsample is present with no encrypted data

This can only happen if the previous subsample does not cover a tile, because each tile has to be protected.

> Shouldn't we rather have a new subsample for a tile only if there is something encrypted before ?

This is already allowed:
> writers SHOULD reduce the number of subsamples as possible. This can be achieved by using a subsample that spans multiple consecutive unprotected OBUs as well as the first unprotected and protected parts of the following protected OBU, if such protected OBU exists.

**Comment by jeanlf** [comment]
that's what I thought, but this is not clear at all. Can't you find a better wording than  "A subsample SHALL be created for each tile.", which is quite confusing?

**Comment by cconcolato** [comment]
A related problem is when the data length for a tile is less than 16. In this case, the tile is not encrypted. Forcing a new subsample is wasteful, and as seen on real content, you may have an entire frame made of very small tiles. In this case, it should be allowed to use a single subsample with 0 encrypted bytes.

**Comment by tomfinegan** [comment]
> What happens if the tile data is bigger than 2^32 bytes ?

I believe that you're describing an invalid stream. A tile with tile data larger than 2^32 bytes would violate LEB128 coding constraints from [section 4.10.5 leb128()](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=36). The OBU_TILE_GROUP or OBU_FRAME that contained such a tile would have to carry a size field with a leb128 value greater than 2^32, no?

**Comment by cconcolato** [comment]
```
0 <= tile_size_bytes_minus_1 <= 3
1 <= TileSizeBytes <= 4
0 <= tile_size_minus_1 <= 2^32-1
1 <= tileSize <= 2^32
```
So indeed you would have to create 2 subsamples for a tile with tileSize = 2^32. Very rare but not forbidden by the rule. The rule does not say you have to create only 1. It says you have to create at least one. This is necessary to ensure that each tile (made of at least 16 bytes) has encrypted data at its start (modulo the block alignment) even in the case of pattern encryption.

**Comment by robUx4** [comment]
> 0 <= tile_size_bytes_minus_1 <= 3

Oops, yes !

> So indeed you would have to create 2 subsamples for a tile with tileSize = 2^32. Very rare but not forbidden by the rule. The rule does not say you have to create only 1. It says you have to create at least one. This is necessary to ensure that each tile (made of at least 16 bytes) has encrypted data at its start (modulo the block alignment) even in the case of pattern encryption.

👍

**Comment by robUx4** [comment]
> 
> 
> > What happens if the tile data is bigger than 2^32 bytes ?
> 
> I believe that you're describing an invalid stream. A tile with tile data larger than 2^32 bytes would violate LEB128 coding constraints from [section 4.10.5 leb128()](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=36). The OBU_TILE_GROUP or OBU_FRAME that contained such a tile would have to carry a size field with a leb128 value greater than 2^32, no?

Indeed:

> It is a requirement of bitstream conformance that the value returned from the leb128 parsing process is less than or equal to (1 << 32) - 1

All `[decode_tile]` we're protecting should fit in an OBU which size is `leb128` coded (in regular or Annex B format). So it cannot exceed 2^32 -1 (or even less with the data before the decode_tile). So the `tileSize` will never be bigger than that and fit in a single `BytesOfProtectedData` in all cases.
