### ISSUE TITLE
On `AV1CodecConfigurationRecord` syntax

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-isobmff#134]
The following array definition looks not correct:

```cpp
unsigned int (8)[] configOBUs;
```

We should probably change it to:

```cpp
unsigned int (8) configOBUs[];
```

**Comment by cconcolato** [comment]
we should use valid SDL syntax, i.e. the proposed change.

**Comment by wantehchang** [comment]
Cyril: In the [draft revision of the AVIF spec](https://aomediacodec.github.io/av1-avif/), we have:

```
class AV1LayeredImageIndexingProperty extends ItemProperty('a1lx') {
    unsigned int(7) reserved = 0;
    unsigned int(1) large_size;
    FieldLength = (large_size + 1) * 16;
    unsigned int(FieldLength)[3] layer_size;
}
```

Is the syntax for the `layer_size` array also wrong?

**Comment by podborski** [comment]
It should simply be changed to `unsigned int(FieldLength) layer_size[3];`

**Comment by cconcolato** [comment]
We agree to fix the SDL.
