### ISSUE TITLE
Links to AV1 spec need an page offset

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-isobmff#135]
Some (or maybe even all) of the links to AV1 spec seem to link to a wrong page number in the PDF document. e.g.: [Delayed Random Access Points](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=206) points to page 206, which is the correct page in AV1 spec. However, since the first 12 pages in the spec. PDF are not numbered the hyperlink actually points to the page number 194 where no such definition can be found.

**Comment by wantehchang** [comment]
Some of the links to the AV1 spec are correct, e.g., the [OBU Header](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=40) links and [Sequence Header OBU](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=41) links are correct. But I also found many links with the wrong page numbers as you reported. Note that not all of the wrong page numbers have a page offset of 12.

**Comment by cconcolato** [comment]
We agree to coordinate with the video spec editors to find a stable way of referencing terms in AV1.

**Comment by cconcolato** [comment]
The AV1 spec is published in 3 different ways:
* A PDF (404 at https://aomediacodec.github.io/av1-spec/av1-spec.pdf)
* A HTML https://aomediacodec.github.io/av1-spec/#metadata-obu-syntax
* Another HTML https://aomedia.org/av1/specification/syntax/#metadata-obu-syntax

**Comment by wantehchang** [comment]
While working on a pull request for this issue, I found a related issue: in the following sentence, the link generated for `chroma_sample_position` is incorrect:

```
The <dfn export>chroma_sample_position</dfn> field indicates the [=chroma_sample_position=] value from the [=Sequence Header OBU=].
```

We want to generate a link to the AV1 spec, but we end up generating a link to the `chroma_sample_position` term defined in this document.

I tried the following obvious fix, but it doesn't work:

```
diff --git a/index.bs b/index.bs
index e5815d6..35242ea 100644
--- a/index.bs
+++ b/index.bs
@@ -107,6 +107,7 @@ url: https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=44; spec: AV1; ty
 url: https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=2; spec: AV1; type: dfn;
        text: buffer_removal_time
        text: byte_alignment
+       text: chroma_sample_position
        text: frame_presentation_time
        text: high_bitdepth
        text: initial_display_delay_minus_1
```

Cyril, Dimitri, do you know how to fix this?

**Comment by cconcolato** [comment]
I think the use of `for` in the `dfn` element can help, see https://speced.github.io/bikeshed/#dfn-autolink and https://github.com/AOMediaCodec/iamf/blob/main/index.bs#L594
