### ISSUE TITLE
Figure 1 issues

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-isobmff#147]
We noticed two issues with the figure 1:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/40244254/171310436-ce79e14a-b7f0-48ba-8576-0f9f8c0b229d.png">

The figure shows that the last tile signals `tile_size_minus_1` as bytes of clear data, however the last tile never includes `tile_size_minus_1` according to [AV1 spec](https://aomediacodec.github.io/av1-spec/#general-tile-group-obu-syntax):

<img width="864" alt="image" src="https://user-images.githubusercontent.com/40244254/171310694-fb03e495-deed-4dba-8d85-925b526ff38e.png">

Second issue is on metadata encryption. The figure shows that metadata OBU is partially encrypted while in the spec we added the constraint that metadata OBUs shall not be protected.

**Comment by cconcolato** [comment]
Done, also updated the note 1 to remove "& MD".
![subsample_encryption](https://user-images.githubusercontent.com/1830314/178399965-03e1dd46-cf2c-4481-ad56-60de26cfddbb.png)
