### ISSUE TITLE
Consider updating the CMAF section to mention `cmf2`

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#158]
The current text says:
> [[CMAF]](https://aomediacodec.github.io/av1-isobmff/#biblio-cmaf) defines structural constraints on ISOBMFF files additional to [[ISOBMFF]](https://aomediacodec.github.io/av1-isobmff/#biblio-isobmff) for the purpose of, for example, adaptive streaming or for protected files. Conformance to these structural constraints is signaled by the presence of the brand [cmfc](https://www.iso.org/standard/71975.html#) in the FileTypeBox.

Since this text was written, CMAF added the brand `cmf2`. We should consider adding it or being generic.

**Comment by podborski** [comment]
Reading through `cmf2` constraints:

> For video CMAF Tracks, the EditBox and in particular the EditListBox shall not be present.  
> 
> For video CMAF Track files as well as any other media types, the EditListBox may be present following the constraints in clause ‎7.5.13.

I wonder if these two restrictions contradict each other?

**Comment by cconcolato** [comment]
@podborski I had written this [document](https://docs.google.com/document/d/1KplnJ-u2GvfG6pMZyb1VzZF2ZNmBX_evcsbWxV-iDcE/edit#heading=h.q61gzxatbxf5) regarding edit lists in CMAF. Unfortunately, never turned it into an MPEG contribution
