### ISSUE TITLE
Add assert-ids to version 1.2.0 of the spec

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#169]
This is for [ComplianceWarden](https://github.com/gpac/ComplianceWarden) support

**Comment by rbouqueau** [comment]
@podborski We're about to resume the work on cw. Don't forget to update [aomrules.py](https://github.com/gpac/ComplianceWarden/blob/master/scripts/aomrules.py) when you feel ready!
