### ISSUE TITLE
Update compliancewarden to reflect coverage in conformance report 

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#201]
The current version of ComplianceWarden used to generate the [conformance report](https://aomediacodec.github.io/av1-isobmff/conformance/) is not up to date with the spec. It is believed the implementation actually implements the normative statements from the spec. The connection between the implemented rules and the assert ids need to be done.
A [Pull Request](https://github.com/gpac/ComplianceWarden/pull/77) is open on ComplianceWarden and needs to be completed.

**Comment by cconcolato** [comment]
The Pull Request has been merged. We need to regenerate the report (and possibly minor tweaks).

**Comment by podborski** [comment]
Done in 7a5bdbc8abbabc548b49fa126cde9c8089a2e0f1
