### ISSUE TITLE
still_picture and codecs parameter

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#32]
Given that still picture and video share profile and level definitions and that you only have to flip the `still_picture` to create a valid AV1 Still picture from an AV1 video keyframe, I don't think it makes sense to signal `still_picture` in the `codecs` parameter. 

The `codecs` parameter is used to determine in advance if a file can be played. First, I don't think it matters for a video player if the sequence contains one image or not. Then, an mp4 file could contain multiple CVSs that each contain a single image. In this case, according to the current spec, the codecs will indicate still_picture=1 but the file will have more than one image, so the promise given by the codecs would not be valid. 

I think we should remove the still parameter from the ISOBMFF codecs.

**Comment by tomfinegan** [comment]
> I think we should remove the still parameter from the ISOBMFF codecs.

Agreed.
