### ISSUE TITLE
Sample Encryption

### ISSUE THREAD

**Issue by jeanlf** [AOMediaCodec/av1-isobmff#34]
The spec currently says all OBU headers shall be in the clear. My understanding of the bitstream format is that the _obu_header_ does not contain the _obu_size_ field, when present. This field should be left unencrypted if we are to walk through encrypted OBUs in a sample.

I would suggest replacing 
`all OBU headers SHALL be unencrypted`

with
`all OBU headers and obu_size field, when present, SHALL be unencrypted`

**Comment by cconcolato** [comment]
Thanks for the feedback. Should be fine now. Reopen if not.
