### ISSUE TITLE
cbcs

### ISSUE THREAD

**Issue by jeanlf** [AOMediaCodec/av1-isobmff#38]
The spec is not very clear how cbcs should be applied. It states for the general case: 
`Tile Group OBUs, Frame OBUs and Tile List OBUs SHALL be encrypted using subsample encryption, with BytesOfProtectedData spanning all complete 16-byte blocks in the data.`

for cenc, this is clarified in the spec. For cbcs, BytesOfProtectedData is ususally more than Nx16, the last block in the pattern being unencrypted. Is the intended behaviour the same as for cenc, ie enforce 16 byte alignment of encrypted payload ? If so this should be clarified. If not, do we want to have, like in avc or hevc cbcs, the first byte of encrypted data after the frame header obu ? 

Additionnaly, but that's more an av1 spec issue, the latest design of the tile group OBU makes it impossible to split/reaggregate motion constrained tiles, unless we allow having only subparts of the obu tile group to be encrypted  - any thoughts on that ?

**Comment by cconcolato** [comment]
Thanks for the comments. Indeed, the spec wasn't very clear. I've tried to clarify in #39. Can you let me know if this addresses your first point?

On the second one about Tile Group OBU, I don't know if the base codec allows it. Would have to be checked. If it is allowed, we could modify the encryption constraints but I'm worried about complexity. This would mean: keep everything in clear until the first `tile_size_minus_1` (included), and keep all the other `tile_size_minus_1` fields also in clear. Also, this would need to force block alignment between those fields, even for the last tile (for which `tile_size_minus_1` is not even coded). WDYT?

**Comment by jeanlf** [comment]
the part on cbcs looks good to me. You may want to add support for cens and cbc1 ?

For the tile group, I agree that it's a lot of added complexity for not very common use case. Maybe just add a note saying that when MCTS stream with encryption has to be encrypted and manipulated on a per-tile base, this can only be done if the encoder produces one tile per tile group OBU.

**Comment by cconcolato** [comment]
Regarding `cens` and `cbc1`, I changed the PR. I don't mention them specifically but I've changed the text to be CTR or CBC specific.
Regarding tiling, it seems very specific at this point. I'll leave the spec as is and we can add the note later on.

**Comment by cconcolato** [comment]
Spec updated, closing.
