### ISSUE TITLE
Initial presentation delay

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#4]
In 16722229699f4b7bc7df0cb242fc25a613f750f1, a sample entry parameter, called `initial_presentation_delay`, was introduced.

This parameter is added  to help players determine how many samples have to be decoded (at the decoding rate of the given level) to be able to guarantee smooth playback. 

It is a hint to enable players to achieve A/V sync without having to wait for the theoretical maximum of 9 samples. It is also explicitly added here to avoid using CTS, and edit lists. 

It is related to the decoder model, not yet finalized in the codec spec. It might be changed depending on how the codec spec is updated.

**Comment by fcartegnie** [comment]
You mean CTTS with decoding time in the edit list media time ?

**Comment by cconcolato** [comment]
I meant that in AV1 the `ctts` box is not used and edit lists should only be used for real edit operations, not to shift the timeline because of B frames.

**Comment by ocrete** [comment]
It's not clear at all to me what that initial_presentation_delay means? Does it means that the decoder normally has a latency of 10 displayed frames (TUs), but that this allows just reducing it? Or does it means that the decoder can output a frame as soon as the first TU is in, but that this TU will take longer to decode?

**Comment by cconcolato** [comment]
> Does it means that the decoder normally has a latency of 10 displayed frames (TUs), but that this allows just reducing it?

Yes. Unless you have information (in the bitstream or out-of-band), you have no guarantee when you start decoding a bitstream that there won't be non-displayable frames in the future that will consume decode time and delay the decoding of displayable frames. In theory, you may have to decode up to 10 frames to have that guarantee. In pratice, it will probably be lower.

**Comment by fcartegnie** [comment]
So that's more or less RASL in hevc terms
