### ISSUE TITLE
Track width, height and aspect ratio

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#40]
The current AV1-ISOBMFF spec says:
> The width and height fields of the VisualSampleEntry SHALL equal the values of max_frame_width_minus_1 + 1 and max_frame_height_minus_1 + 1 of the Sequence Header OBU applying to the samples associated with this sample entry.

> As specified in [ISOBMFF], the width and height in the VisualSampleEntry are specified in square pixels. If the video pixels are not square, then a pasp box SHALL be included and the track header width and height SHOULD match the values of max_frame_width_minus_1 + 1 and max_frame_height_minus_1 + 1 after the pasp ratio has been applied.

However the AV1 spec has an additional notion of render_width:
>The render size is provided as a hint to the application about the desired display size. It has no effect on the decoding process.

Note that like frame width and height, this can change from frame to frame, and there is not max_render_width/height.

Should we keep the current text or change it to say: 
- track width and height should (or maybe shall) be set to the max render width and height (which defaults to max_frame_width/height if render width/height is not used);
- pasp shall be included if render aspect ratio differs from frame aspect ratio and shall match the difference?

**Comment by tomfinegan** [comment]
With render width/height being an application level hint I don't think it needs to be carried at the container level. I think we should keep the existing text, but perhaps add a note? Something like:

_AV1 specifies a render size that serves as a hint to applications about desired display size. The render size is allowed to change arbitrarily on a frame-by-frame basis. When an AV1 decoder provides a render size it overrides the value specified in the VisualSampleEntry._

Maybe that can't be a note and needs to be text added as a new paragraph after the existing text quoted in your comment.

My concern is that if we use render size in ISOBMFF we cannot write a VisualSampleEntry correctly without reading all the frames in a sequence. A muxer would have to inspect all frame headers and keep the maximums around until it was going to write the VisualSampleEntry, no?

**Comment by cconcolato** [comment]
> My concern is that if we use render size in ISOBMFF we cannot write a VisualSampleEntry correctly without reading all the frames in a sequence. A muxer would have to inspect all frame headers and keep the maximums around until it was going to write the VisualSampleEntry, no?

I don't think we should change the width and height in the VisualSampleEntry. For all codecs, they usually correspond to the coded pixels (video samples) not the displayed ones. The only question is how to set the track width and height and sample entry pasp. For the former two, given that many players ignore them, just saying 'should be set to the max render size' should suffice. My main concern is the aspect ratio. How would anamorphic videos be signaled in AV1 bitstreams?

**Comment by tomfinegan** [comment]
> My main concern is the aspect ratio. How would anamorphic videos be signaled in AV1 bitstreams?

How about:

_When an AV1 bitstream carried in ISOBMFF carries a pasp box and has render_size present in the AV1 bitstream, the render_size specified by the AV1 bitstream SHOULD be used to determine display dimensions._

?
