### ISSUE TITLE
zero OBU in the configOBU is not good for playback

### ISSUE THREAD

**Issue by robUx4** [AOMediaCodec/av1-isobmff#46]
The current spec says that `The configOBUs field contains zero or more OBUs`. That means the Sequence Header OBU may not be found in there. It is a problem to select the right decoder on playback. For example hardware decoders have different GUID for different profile of the same codec. Some hardware decoder may not support all profiles will a software decoder might. It's always better to have this information before parsing the sample data.

Would it be possible to restrict the configOBU to mandate having the Sequence Header OBU in there ? Also it should be the first OBU of the configOBU to make it easy/fast to detect the profile from the codec extra data.

Or at least make it a a SHALL statement that implies there must be good reasons not to do it. But IMO there shouldn't be.

**Comment by fcartegnie** [comment]
That's not different from HEVC DCR without completeness or H264 with zero SPS/PPS. There's a use case for this.
The real issue is not having any profile, chroma or useful information in the DCR itself.

**Comment by tomfinegan** [comment]
What happens with mandatory SH OBU presence when there's a decoder model and operating points info? The one in configOBUs (or CodecPrivate in MKV's case) won't always be correct.

**Comment by robUx4** [comment]
In the case of MKV we took the same requirements as the requirements for a Coded Video Sequence: only the [operating_parameters_info] data can change. As I understand it. it's valid for this value to change in a Coded Video Sequence which is what we try to handle.
If the values change during the stream they must be part of the bitstream that's inside the MKV/WebM. If not it can be omitted (but the one right after a differing one also needs to be in the stream).

For ISOBMFF you mention that the SH OBU needs to be prepended to every sync point. ```From any sync sample, an AV1 bitstream is formed by first outputting the OBUs contained in the AV1CodecConfigurationBox and then by outputing all OBUs in the samples themselves, in order, starting from the sync sample.``` So if there's a differing one that's stored in the stream, it would come after the prepended one and be used properly.

**Comment by cconcolato** [comment]
> That's not different from HEVC DCR without completeness or H264 with zero SPS/PPS. There's a use case for this.

I agree. The use case is live streaming. You might not know the configuration in advance.


> So if there's a differing one that's stored in the stream, it would come after the prepended one and be used properly.

Having different SH within a Temporal Unit is an invalid bitstream I think.

**Comment by robUx4** [comment]
> I agree. The use case is live streaming. You might not know the configuration in advance.

It would seem odd that an encoder is not capable of producing the Sequence Header OBU that will remain valid for the lifetime of the stream before coding any frame. Especially an encoder used for live streaming.

But even in that case I don't think creating the header way when the first frame arrives is a major issue. If latency is an issue, then an encoder that gives out the information as soon as possible should be preferred in this scenario.

**Comment by cconcolato** [comment]
> It would seem odd that an encoder is not capable of producing the Sequence Header OBU that will remain valid for the lifetime of the stream before coding any frame. Especially an encoder used for live streaming.

Why? The Sequence Header contains many elements that could be changed from a CVS to the next depending on the type of content for example.



> But even in that case I don't think creating the header way when the first frame arrives is a major issue. If latency is an issue, then an encoder that gives out the information as soon as possible should be preferred in this scenario.

I don't understand.

**Comment by robUx4** [comment]
> Why? The Sequence Header contains many elements that could be changed from a CVS to the next depending on the type of content for example.

In Matroska there's the requirement that a Segment contains one CVS. If the CVS param changes it must be a different Segment (the highest level encapsulation) which can be concatenated to the previous one.
If you want to allow changing CVS in the same isobmff file maybe it should probably be a separate mapping like H264 or H265. That would allow the one with a single CVS to be more restrictive.

**Comment by robUx4** [comment]
> But even in that case I don't think creating the header way when the first frame arrives is a major issue. 

I think "way" was the wrong word but I don't remember what I meant :/

> If latency is an issue, then an encoder that gives out the information as soon as possible should be preferred in this scenario.

If you don't know the SH OBU in advance that means the encoder is not totally suitable for live streaming (assuming with low latency). As you said, it cannot create the header/initialization segment early enough. Maybe another encoder design would suit better the constraints.

**Comment by tomfinegan** [comment]
Closing this. Please move discussion over to https://github.com/AOMediaCodec/av1-isobmff/issues/50 if you'd like to pursue further changes.

**Comment by robUx4** [comment]
So far this has not been addressed there is still `sequence_parameters_present` and `zero or more OBUs`. The profile itself is not sufficient to decide if a decoder is suitable or not. For example I don't except a lot of AV1 HW decoders to support 12 bits decoding anytime soon. But can't know from the minimal header if that's what the file contains or not.

**Comment by tomfinegan** [comment]
> So far this has not been addressed there is still sequence_parameters_present and zero or more OBUs. The profile itself is not sufficient to decide if a decoder is suitable or not. For example I don't except a lot of AV1 HW decoders to support 12 bits decoding anytime soon. But we can't know from the minimal header if that's what the file contains or not.

Please move discussion over to #50.
