### ISSUE TITLE
Presence of basic stream information in AV1CodecConfigurationBox

### ISSUE THREAD

**Issue by jamrial** [AOMediaCodec/av1-isobmff#50]
This is an attempt at combining the suggestions about the contents of the AV1CodecConfigurationBox currently spread across separate Issues and PRs.

The definition of AV1CodecConfigurationBox in the spec as it stands now may not be optimal for the reasons explained in other Issues/PRs and quoted below. Allowing no OBUs is only recommendable if basic stream information, like profile, level and bitdepth, is already available independently [1] [2]. Otherwise, parsers will be forced to use sample data to find out if decoding is even possible in the first place. This is an unnecessary complexity, and may even be a hindrance for hardware decoding scenarios.

Based on the above, as an ffmpeg developer handling support for AV1 in isobmff and Matroska I'd like to request for a final decision to be made about this subject. For example, and summarizing what's been said in the quoted issues/PRs below:

Option 1: Define a few extra fields in AV1CodecConfigurationBox to store stream profile (seq_profile), level (seq_level_idx[0]), bit depth (BitDepth), and maybe OBU count of each of types Sequence Header and Metadata present in the box (and thus enforcing ordering). This will require the box version to be bumped to 1, and will be enough for any parser to choose to continue or bail out after reading only a few bytes.
Option 2: Merge [3], disallowing empty configOBUs.
Option 3: Leave things as is, and close every related issue/PR.

[1] https://github.com/AOMediaCodec/av1-isobmff/issues/7#issuecomment-406257234 (misplaced relevant comment in an unrelated Issue)
[2] https://github.com/AOMediaCodec/av1-isobmff/issues/46
[3] https://github.com/AOMediaCodec/av1-isobmff/pull/47

**Comment by robUx4** [comment]
How about Option 1b: Define a few extra fields in AV1CodecConfigurationBox to store stream profile (seq_profile), level (seq_level_idx[0]), bit depth (BitDepth) and no OBUs at all.
In the case of Matroska it would be enough for playback at the rest of the data can be set at the container level (including the HDR metadata).
If ISOBMFF requires the 'main' OBUs to be stored somewhere it could be in a different box ?

**Comment by jamrial** [comment]
>How about Option 1b: Define a few extra fields in AV1CodecConfigurationBox to store stream profile (seq_profile), level (seq_level_idx[0]), bit depth (BitDepth) and no OBUs at all.

No, I'd very much rather keep the presence of Sequence Header and Metadata OBUs as it's currently defined. Let's not make things more complex than they need to be. What needs to be decided is if the av1C box is expanded to have the same usefulness as avcC and hvcC for simple and complex parsers alike, or not.

>If ISOBMFF requires the 'main' OBUs to be stored somewhere it could be in a different box ?

Storing global configuration OBUs and assorted initialization fields is the entire point of the AV1CodecConfigurationBox. No need to add another box for the same purpose.

As mentioned, with option 1 the newly added fields would be useful for parsers that want basic data to decide to continue or bail out, but more advanced parsers and decoders can and will, if present, use the rest of the initialization data stored in those two OBU types before sample data is processed.

**Comment by PauKerr** [comment]
I see BitDepth as being a codec-agnostic value that may be better suited as
an image attribute like Pixel Aspect Ratio ('pasp'). This information could
parsed without understanding the OBU syntax.

**Comment by tomfinegan** [comment]
I prefer option 2 from @jamrial's initial comment in this issue. @cconcolato is out of the office and unavailable until tomorrow. We should be able to pick this discussion up and move forward upon his return.

**Comment by tomfinegan** [comment]
> I prefer option 2

Note, also fine with option 3. 

With option 2, In a live streaming case, I don't like that an app may have to generate init data with space reserved in configOBUs so it can go back and fill it in. It's not the end of the world, but, and using Vorbis audio in WebM as an example, I always found it clumsy to have to reserve space in CodecPrivate for Vorbis setup data only to go back and add the data followed by a Void element to consume the remaining reserved space.

**Comment by jamrial** [comment]
As mentioned before, option 3 is the least ideal. Right now, allowing having no seq header is going to make parsers for a bunch of cases unnecessarily complex. Think browsers, phones and other devices where firing up a hardware decoder is expensive, and being able to know if decoding is possible before sample data is available to bail out or use a fallback decode path is the ideal scenario.

I'm partial to option 1 myself, being the closest to the proven init method used in isobmff by avcC and hvcC: Basic stream init data, followed by zero or more OBUs. It covers most usecases as described by @fcartegnie in the quoted issue comments i listed earlier.

**Comment by tomfinegan** [comment]
My concern with options one and two is that  both introduce the requirement that a sequence header be available before an encode pipeline can output a sample entry.

I dislike option one more than two because it forces muxers to parse sequence headers to obtain the values you'd like you see in the added fields.

**Comment by robUx4** [comment]
> With option 2, In a live streaming case, I don't like that an app may have to generate init data with space reserved in configOBUs so it can go back and fill it in. It's not the end of the world, but, and using Vorbis audio in WebM as an example, I always found it clumsy to have to reserve space in CodecPrivate for Vorbis setup data only to go back and add the data followed by a Void element to consume the remaining reserved space.

IMO you are saying that the codec private of Vorbis is inconvenient in live streaming so it would work better without.

IMO it's an issue with the design of the encoder you are using. For live purposes it should be able to tell you the private data it's going to use for the lifetime of the stream, even if it means caching a few buffers ahead on startup (which sucks for live streaming).

The same applies here IMO. In the "offline" case forcing one SH OBU is not an issue. For live purposes it means a certain design requirement for the encoder. And it's early enough to decide if that's something we want to enforce or not.

**Comment by robUx4** [comment]
I fear that if we allow zero SH OBU in the header that's what most people use because, as you said for Vorbis, it's often more convenient. In the end you might as well never put it in the header since you'll have to handle the least favorable case anyway (unless there's an "offline" profile and a "live streaming" profile).

**Comment by robUx4** [comment]
Also how are you going to fill the `initial_presentation_delay` of the `AV1CodecConfigurationRecord` in a live stream if you don't get that information from the SH OBU and/or early enough from the decoder ?

Or you assume it will never be present in that case ? Which should probably be mentioned: if there's no SH OBU then `initial_presentation_delay_present` MUST be 0.

**Comment by fcartegnie** [comment]
> Option 1 would keep the current "zero or more OBUs" requirement, so using your example above, if a Seq Header is not available before sample data you wouldn't have to worry about reserving a guessed amount of space for it in av1C/CodecPrivate. It would instead be a fixed amount of bytes that you can later go back and seamlessly rewrite with updated values if required.

Most muxers write header at the end, or start output when everything is known.
I don't think your should put your own muxer implementation prealloc considerations here.

**Comment by fcartegnie** [comment]
> I fear that if we allow zero SH OBU in the header that's what most people use because, as you said for Vorbis, it's often more convenient. In the end you might as well never put it in the header since you'll have to handle the least favorable case anyway (unless there's an "offline" profile and a "live streaming" profile).

This is implied by the container mapping. 
Ex: avc1 requires xPS out of band, no xPS in the stream, which seems correct if the configuration never changes. No overhead in samples.
others avcN versions allows a mix of none or partial xPS and in none or partial xPS in samples, for streams that can change configuration, while being able to rebuild consistent configuration when doing random access.
Same for hev1 vs hevc

**Comment by fcartegnie** [comment]
> I dislike option one more than two because it forces muxers to parse sequence headers to obtain the values you'd like you see in the added fields.

If the mapping has requirements on the content of the first sample, you'll still need to sync and delay muxing anyway. That's no different from most codecs, assuming information was not already provided as extradata.

**Comment by fcartegnie** [comment]
> Also how are you going to fill the initial_presentation_delay of the AV1CodecConfigurationRecord in a live stream if you don't get that information from the SH OBU and/or early enough from the decoder ?

You're supposed to be in control of the encoder params, so you know at least how you configured it.
Except Smooth streaming, all live streams do only provide minor parameters, such as profile.

**Comment by jamrial** [comment]
>Most muxers write header at the end, or start output when everything is known.
I don't think your should put your own muxer implementation prealloc considerations here.

That was @tomfinegan concern, which applies mainly to Matroska. I simply stated that it would be no different than how such a muxer would do it with avcC and hvcC.

>Or you assume it will never be present in that case ? Which should probably be mentioned: if there's no SH OBU then initial_presentation_delay_present MUST be 0.

The spec already states "If an ISOBMFF writer cannot verify the above procedure, initial_presentation_delay_present SHALL be set to 0."

**Comment by tomfinegan** [comment]
> The spec already states "If an ISOBMFF writer cannot verify the above procedure, initial_presentation_delay_present SHALL be set to 0."

Right, and initial_presentation_delay_present was added to the spec to avoid requiring that muxers know how to parse Sequence Header OBUs.

**Comment by jamrial** [comment]
I'll repost https://github.com/AOMediaCodec/av1-isobmff/pull/57#issuecomment-411933626 here plus some additions, since it's the proper place.

Following the changes introduced by #57, at the very least Seq_profile needs to be an obligatory field. Every other field added (except maybe seq_level_idx_0 and bitdepth) is unnecessary since unlike the aforementioned one they have no use when choosing a decoder early during initialization, so they could be removed or left as optional. But without Seq_profile, if you still allow no seq obus then all the effort made in that pull request will be pointless and just leave us with a more complex av1C box. If parsers may still need to look at sample data just to get basic initialization information before a decoder can be chosen, then the current box will have virtually no benefits over the old one.

Muxers have had no issues filling the obligatory profile field of avcC, or even every field in vpcC. So I don't understand why they would with the profile field in av1C.
You're focusing too much in making muxer implementations as simple as possible by working around something that hasn't been a problem before, at the cost of making parsers and demuxers in players more complex with something that's known to be a headache.

For that matter, may i request the first byte of this box to be distinguishable from the first header byte of a raw OBU? Something like the very first bit of the AV1CodecConfigurationRecordv1 struct being always 1 (The exact opposite of the obu_forbidden_bit in a raw obu header), or making the reserved bits be 5 instead of 4 (since "type", the second field in a raw obu header, can't be 0), or directly making the reserved field 8 bits long?

**Comment by tomfinegan** [comment]
Requiring the presence of seq_profile in the configuration record doesn't seem to be an onerous burden. That's easily extracted in encode and remux scenarios (since it's always the first 3 bits of the SH OBU).

Extracting seq_level_idx[0] and bit depth from the SH OBU is non-trivial, and doing so when remuxing will require that either muxers or demuxers implement full support for parsing of AV1 SH OBUs. I believe these two fields must remain optional.

I've increased the number of reserved bits as well.

PR here: https://github.com/AOMediaCodec/av1-isobmff/pull/64

**Comment by jamrial** [comment]
Fine by me. I assume a hardware decoder that's Main profile compliant is expected to support both 8bit and 10bit streams, so having it alone without bit_depth should be ok for the purpose of choosing a decoder.

**Comment by fcartegnie** [comment]
> Fine by me. I assume a hardware decoder that's Main profile compliant is expected to support both 8bit and 10bit streams, so having it alone without bit_depth should be ok for the purpose of choosing a decoder.

So you'll need a new profile if the codec evolves with a new bit depth

**Comment by tomfinegan** [comment]
Closing this since https://github.com/AOMediaCodec/av1-isobmff/pull/64 has been merged. If anyone feels this needs further discussion, please feel free to reopen the issue.

**Comment by robUx4** [comment]
> Extracting seq_level_idx[0] and bit depth from the SH OBU is non-trivial, and doing so when remuxing will require that either muxers or demuxers implement full support for parsing of AV1 SH OBUs.

I don't see the problem. If the fields are not optional, remuxing will always contain the information in the source (otherwise it's invalid and thus may or may not be supported depending on the muxer choices). The same information will be available in Matroska.

**Comment by jamrial** [comment]
My main beef about the optional fields is that muxers will most likely never bother to fill them. Especially since it's an "all or none" situation.

>Extracting seq_level_idx[0] and bit depth from the SH OBU is non-trivial, and doing so when remuxing will require that either muxers or demuxers implement full support for parsing of AV1 SH OBUs.

Looking the spec again, i noticed that in Section 5 (https://aomediacodec.github.io/av1-isobmff/#codecsparam) you already require the muxer to know profile, level, tier and bitdepth in a DASH or similar muxing process, so all these values will have to be fetched in such scenario. Therefore i don't think it's unreasonable to also require them to generate a fully featured AV1CodecConfigurationRecordv1.

>Closing this since #64 has been merged. If anyone feels this needs further discussion, please feel free to reopen the issue.

I tried, but I can't reopen it even though i created it because you closed it as a collaborator to the project.

**Comment by tomfinegan** [comment]
> My main beef about the optional fields is that muxers will most likely never bother to fill them. Especially since it's an "all or none" situation.

I agree it's not ideal, but the design of the SH OBU, specifically the complex parsing needed to access the fields beyond seq_profile, has created an unfortunate situation that's not easily remedied. 

> Looking the spec again, i noticed that in Section 5 (https://aomediacodec.github.io/av1-isobmff/#codecsparam) you already require the muxer to know profile, level, tier and bitdepth in a DASH or similar muxing process, so all these values will have to be fetched in such scenario. Therefore i don't think it's unreasonable to also require them to generate a fully featured AV1CodecConfigurationRecordv1.

In a DASH encoding scenario wouldn't you always know all of the required parameters? I have a difficult time envisioning a pipeline producing DASH presentations that does not have access to all of the required information through other means. AV1CodecConfigurationRecordv1 limits the requirements of the muxing implementation to avoid forcing an app to fully parse SH OBUs in a remux scenario. (i.e. LOBF or Annex-B -> ISOBMFF, where the only option would be to parse the SH OBU).

> I tried, but I can't reopen it even though i created it because you closed it as a collaborator to the project.

Reopening to allow further discussion, though I disagree that any further changes are needed.

**Comment by jamrial** [comment]
>In a DASH encoding scenario wouldn't you always know all of the required parameters? I have a difficult time envisioning a pipeline producing DASH presentations that does not have access to all of the required information through other means. AV1CodecConfigurationRecordv1 limits the requirements of the muxing implementation to avoid forcing an app to fully parse SH OBUs in a remux scenario. (i.e. LOBF or Annex-B -> ISOBMFF, where the only option would be to parse the SH OBU).

In a remuxing scenario with raw bitstreams as source you're required to parse the SH OBU to get other information meant for other boxes, like video dimensions for VisualSampleEntry and the TrackHeaderBox, as stated in Section 2.2.4, not just stuff for AV1CodecConfigurationRecordv1. This means that you parse way beyond seq_level_idx[0] and seq_tier[0]. So i think they can reasonably be mandatory.

bit_depth is a different story, since that one does require go all the way down to color_config(), so it plus monochrome/chroma can remain optional. I'd rename the struct from sequence_parameters to color_parameters, though, if the above change is implemented.

**Comment by tomfinegan** [comment]
> In a remuxing scenario with raw bitstreams as source you're required to parse the SH OBU to get other information meant for other boxes, like video dimensions for VisualSampleEntry and the 

@jamrial point taken on the above. Added a new PR. Note: For now this is posted to facilitate discussion.

**Comment by tdaede** [comment]
This was a huge improvement, though I'd comment that my preference would still be to just stuff the entire sequence header OBU in at this point (option 2).

I'm still a little confused about the "non-mandatory" fields that don't have a SHALL. If I can't rely on them being set by a muxer, what can I use them for?

**Comment by jamrial** [comment]
> Though I'd comment that my preference would still be to just stuff the entire sequence header OBU in at this point (option 2).

These fields were suggested and implemented in order to keep the presence of OBUs optional while also having enough init info when the SH is not included. Making the SH OBU mandatory is not good for muxers in some scenarios.

The current state of AV1CodecConfigurationRecordv1 is IMO pretty good and doesn't really need changes.

**Comment by robUx4** [comment]
> What do you mean you don't see the problem? I don't understand-- do you think that all muxers should be required to implement a full SH OBU parser? Or, are you returning to the argument that the SH OBU should be required in configOBUs?

No I meant remuxing from ISOBMFF or Matroska. But I see James mentioned a `remuxing scenario with raw bitstreams` in which case the SH OBU has indeed to be parsed.

IMO it's not such a burden. Remuxing from TS is always a problem for example because you have to parse everything and extract the meaningful bits to remux to something else. A bit of complexity is expected here, it's not unheard of. 

I see the changes have been made so it's all good :)

**Comment by fcartegnie** [comment]
> IMO it's not such a burden. Remuxing from TS is always a problem for example because you have to parse everything and extract the meaningful bits to remux to something else. A bit of complexity is expected here, it's not unheard of.

That's not entirely true.
mpeg TS has more than a way to pass extradata, and descriptions are one : AC3 and DTS have all their parameters in descriptors, for example.

Of course, as long as multimedia library people accept to workaround/playback mpeg TS steams without mandatory descriptors or PAT/PMT, that's just a shot in the foot.
