### ISSUE TITLE
Subsample structure

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#6]
A sample is a TU. The sample group `AV1MultiFrameSampleGroupEntry` indicates which TUs have multiple frames, but there is no easy way to access the frames without scanning all OBUs. Should we define what `codec_specific_parameters` means for AV1 samples? for finding frames within a sample, or tile groups within a frame?

**Comment by tdaede** [comment]
I think that the OBU scan is fast enough that adding more signaling is likely to cause more harm than it's worth (by nature of being possible to set incorrectly).

**Comment by cconcolato** [comment]
Yes OBU scanning is fast enough to determine frame boundaries. What about tiles?
Anyway, I don't think that is needed for v1 of the spec. It could be defined later if need be.

**Comment by tdaede** [comment]
There usually won't be enough tiles to matter, and you at least only need to scan one tile group. Most of the time you are going to not be seeking to a random tile, but dispatching them to threads in the order they appear.

If you had some application where you did need really fast random seeking without reading the whole sample, it might make more sense to have each in a tile group and then some sort of OBU pointer structure, I suppose.

**Comment by cconcolato** [comment]
I agree. Closing as this is not needed for now. Can be reopened in the future if needed.
