### ISSUE TITLE
Clarify presence of Sequence Header OBUs in Sync Samples

### ISSUE THREAD

**Issue by jamrial** [AOMediaCodec/av1-isobmff#67]
The spec in Section 2.3.4 says the following:

> The configOBUs field contains zero or more OBUs. Any OBU may be present provided that the following procedures produce compliant AV1 bitstreams:
> - From any sync sample, an AV1 bitstream is formed by first outputting the OBUs contained in the AV1CodecConfigurationBox and then by outputing all OBUs in the samples themselves, in order, starting from the sync sample.

Then, in Section 2.4 it says:

> If an AV1 Sample is signaled as a sync sample (in the SyncSampleBox or by setting sample_is_non_sync_sample to 0), it SHALL be a Random Access Point as defined in [AV1], i.e. satisfy the following constraints:
> - Its first frame is a Key Frame that has show_frame flag set to 1,
> - It contains a Sequence Header OBU before the first Frame Header OBU.

Does this mean the sync sample should effectively contain all the required OBUs defined in the AV1 spec to be qualified as a RAP, or are these constrains implicitly taking into account the bitstream assembly procedure described in Section 2.3.4?
In other words, can the Sequence Header OBU be omitted from the sync sample if it's already in configOBUs? Matroska for example currently allows that.

**Comment by cconcolato** [comment]
> Does this mean the sync sample should effectively contain all the required OBUs defined in the AV1 spec to be qualified as a RAP?

Yes. 


> are these constrains implicitly taking into account the bitstream assembly procedure described in Section 2.3.4?

No. The assembly procedure is there to constrain what can be put in the configOBUs field. In particular, if you put an SH OBU, the consequence of the assembly is that it has to be identical (except for operating_parameters_info).

**Comment by jamrial** [comment]
Alright, thanks for the clarification. I'll reopen if i have another doubt or a suggestion.
