### ISSUE TITLE
The presentation_delay bits don't align to 8 bits

### ISSUE THREAD

**Issue by robUx4** [AOMediaCodec/av1-isobmff#76]
There are 3 times 8 bits before `initial_presentation_delay_minus_one` and `initial_presentation_delay_minus_one` + `initial_presentation_delay_minus_one|reserved` is 5 bits and right after are the `configOBUs`. I think there should be some padding here. 

Also the `initial_presentation_delay_present` could replace the `reserved` before it and the `initial_presentation_delay_minus_one|reserved` use 8 bits.

**Comment by jamrial** [comment]
>   unsigned int (1) marker = 1;
>   unsigned int (7) version = 1;

>   unsigned int (3) seq_profile;
>   unsigned int (5) seq_level_idx_0;

>   unsigned int (1) seq_tier_0;
>   unsigned int (1) high_bitdepth;
>   unsigned int (1) twelve_bit;
>   unsigned int (1) monochrome;
>   unsigned int (1) chroma_subsampling_x;
>   unsigned int (1) chroma_subsampling_y;
>   unsigned int (2) chroma_sample_position;

>   unsigned int (3) reserved = 0;
>   unsigned int (1) initial_presentation_delay_present;
>   if (initial_presentation_delay_present) {
>     unsigned int (4) initial_presentation_delay_minus_one;
>   } else {
>     unsigned int (4) reserved = 0;
>   }

>   unsigned int (8)[] configOBUs;

It aligns perfectly. I don't get what you're saying. The 3 reserved bits before initial_presentation_delay_minus_one are acting as padding to achieve alignment.

**Comment by tomfinegan** [comment]
Yeah, I'm confused:

> There are 3 times 8 bits before `initial_presentation_delay_minus_one` ...

+ 3 `reserved` bits.  `initial_presentation_delay_present` and `initial_presentation_delay_minus_one`
are in the same byte. `configOBUs` is also aligned.

**Comment by cconcolato** [comment]
Looking at https://github.com/Matroska-Org/matroska-specification/blob/av1-mappin/codec/av1.md, the structures are not in sync. But it says:
> The CodecPrivate consists of 4 octets similar to the first 4 octets of the ISOBMFF AV1CodecConfigurationBox

I just think the comment was not based on our latest spec. Closing the issue. Reopen with more details if needed.
