### ISSUE TITLE
Section 4 on Common Encryption should be more explicit.

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [AOMediaCodec/av1-isobmff#8]
Current text:
...SHALL use [CENC]. Both cenc and cbcs scheme types are permitted.

Recommended text:
...SHALL use [CENC] and SHALL use scheme type 'cenc' or scheme type 'cbcs'.

**Comment by cconcolato** [comment]
Do you want to forbid other modes (cbc1, cens) and future ones we don't know about? Usually that is done in derived spec, e.g. depending on the application. Even CMAF does not restrict that. It defines constraints for 'cenc' and 'cbcs' and presentation profiles for them, but is silent about the other modes.

**Comment by swenkeratmicrosoft** [comment]
After speaking internally with a few other folks interested in this spec, they are in agreement that the existing wording is fine to be consistent with CMAF.  Consider my feedback rescinded.

Thanks,

-Sam
swenker
Unnecessarily circumlocutory narcissistic signature omitted.
