### ISSUE TITLE
Spanning Subsamples?

### ISSUE THREAD

**Issue by tinskip** [AOMediaCodec/av1-isobmff#80]
I believe the language "Protected samples SHALL be exactly spanned by one or more contiguous subsamples" to be confusing.  What is it trying to convey?

**Comment by cconcolato** [comment]
This is similar wording to the first sentence of 9.5.2.2 in CENC. It is meant to say that:
a) you may have one or more subsamples, and that there shall be no gap between
b) and not hole before the first one or the last one.
In other words, a sample should be entirely covered by the subsamples. All bytes should either be in the BytesOfClearData or in the BytesOfProtectedData of a subsample.

I don't think any change is needed. Do you have a suggestion for better wording? If so, we could ask for an update of the CENC spec and update the AV1-ISOBMFF spec in a future version. Reopen as needed.
