### ISSUE TITLE
"Profile 0" in Section 5 of the spec should be "Main Profile"

### ISSUE THREAD

**Issue by jamrial** [AOMediaCodec/av1-isobmff#82]
> For example, codecs="av01.0.04M.10.0.112.09.16.09.0" represents AV1 profile 0, level 3.0, Main tier, 10-bit content, non-monochrome, with 4:2:0 chroma subsampling co-located with (0, 0) luma sample, ITU-R BT.2100 color primaries, ITU-R BT.2100 PQ transfer characteristics, ITU-R BT.2100 YCbCr color matrix, and studio swing representation.

> The string codecs="av01.0.01M.08" in this case would represent AV1 profile 0, level 2.1, Main tier, 8-bit content with 4:2:0 chroma subsampling, ITU-R BT.709 color primaries, transfer characteristics, matrix coefficients, and studio swing representation.

In both paragraphs, it should read "Main Profile" instead.

**Comment by cconcolato** [comment]
Yeah, that would be a nice editorial change. Given the workplan agreed in the AOM Codec WG, I'm not sure we can do any change to the spec at this stage. But, I don't think that's wrong, is it? The AV1 spec says:
> “Main” compliant decoders must be able to decode streams with seq_profile equal to 0.
