### ISSUE TITLE
MasteringDisplayColourVolumeBox != SMPTE2086MasteringDisplayMetadataBox

### ISSUE THREAD

**Issue by fcartegnie** [AOMediaCodec/av1-isobmff#85]
> NOTE: The MasteringDisplayColourVolumeBox mdcv and ContentLightLevelBox clli have identical payload to the SMPTE2086MasteringDisplayMetadataBox SmDm and ContentLightLevelBox CoLL, except that they are of type Box and not FullBox.

I don't have a recent spec, but according to
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mov.c#L5311
primaries payload is GBR

and the SMPTE one
https://www.webmproject.org/vp9/mp4/
primaries payload is RGB

**Comment by cconcolato** [comment]
Good catch! Thanks.

The MIAF spec in which the boxes are currently defined (they are meant to move to ISOBMFF spec soon) says:
> [mdcv] provides information about the colour primaries, white point, and mastering luminance in the content and may be present in a VisualSampleEntry. It is functionally equivalent to, and described in, the Mastering display colour volume SEI in Rec. ITU-T H.265 | ISO/IEC 23008-2, with the addition that the provisions of CTA-861-G in which zero in some cases codes an unknown value may be used.

Rec. ITU-T H.265 | ISO/IEC 23008-2 says:
> display_primaries_x[ c ] and display_primaries_y[ c ] specify the normalized x and y chromaticity coordinates, respectively, of the colour primary component c of the mastering display in increments of 0.00002, according to the CIE 1931 definition of x and y as specified in ISO 11664-1 (see also ISO 11664-3 and CIE 15). For describing mastering displays that use red, green and blue colour primaries, it is suggested that index value c equal to 0 should correspond to the green primary, c equal to 1 should correspond to the blue primary and c equal to 2 should correspond to the red colour primary (see also Annex E and Table E.3). The values of display_primaries_x[ c ] and display_primaries_y[ c ] shall be in the range of 0 to 50 000, inclusive.

Notice that the order uses a 'should'!! 

@dwsinger I think the MIAF/ISOBMFF spec should be clearer. Is it following the 'should' from HEVC? Probably given that it is already implemented in some tools... In that case, that should be explicit.  

@fcartegnie Regarding the AV1-ISOBMFF spec, we could either take out the note or highlight the difference. Any preference?

**Comment by fcartegnie** [comment]
> @fcartegnie Regarding the AV1-ISOBMFF spec, we could either take out the note or highlight the difference. Any preference?

At least a big warning. I'd bet that's will trigger never-ending bugs as ppl will read or store GBR like mpeg in SdSm and try to read any with or without version.
The real issue is to have 2 boxes for the same purpose.

**Comment by jamrial** [comment]
Unless i'm reading things wrong, there is also the fact that the SmDm box stores the values as 0.16, 24.8 and 18.14 fixed point values as stated in https://www.webmproject.org/vp9/mp4/, whereas mdvc as quoted above stores them as unsigned 16-bit values.

The contents of CoLL however are the same as clli.

**Comment by cconcolato** [comment]
The devil is in the details ...

According to Rec. ITU-T H.265 | ISO/IEC 23008-2:
> white_point_x and white_point_y specify the normalized x and y chromaticity coordinates, respectively, of the white point of the mastering display in normalized increments of 0.00002, according to the CIE 1931 definition of x and y as specified in ISO 11664-1 (see also ISO 11664-3 and CIE 15). The values of white_point_x and white_point_y shall be in the range of 0 to 50 000.

and 

> max_display_mastering_luminance and min_display_mastering_luminance specify the nominal maximum and minimum display luminance, respectively, of the mastering display in units of 0.0001 candelas per square metre. min_display_mastering_luminance shall be less than max_display_mastering_luminance.

@jamrial you're right, but not that in `mdcv` the unit are also not the same for each field: increments of 0.00002 for the first ones, and of 0.0001 for the last two.

**Comment by fcartegnie** [comment]
> Unless i'm reading things wrong, there is also the fact that the SmDm box stores the values as 0.16, 24.8 and 18.14 fixed point values as stated in https://www.webmproject.org/vp9/mp4/, whereas mdvc as quoted above stores them as unsigned 16-bit values.

I don't see how both SMTP values can be integral and non integral.
Are you sure that's not just the 2086 values which are usually stored as an opaque 16bits integer ?

**Comment by cconcolato** [comment]
Regarding the interpretation of the the `mdcv` data, here is some info I have received by email:
> in relationship to the order of the primaries, the determination of the primaries is done based on where they lie in the CIE 1931 xy chromaticity diagram. So one would have to take the x and y coordinates of the three display_primaries that you are transmitting, place them on that diagram, and then figure out which one is green (the one on the top), red (bottom right), or blue (bottom left). It is “suggested” that the order is GBR, and one could signal the values in that order, but one could switch them and derive the order based on where the values lie. It just requires some simple math and certain assumptions about the placement of those points (although someone could make a weird triangle that has lets say two green points and a point in the magenta colour that also defines a triangle, that does not make much sense in terms of applications; I guess you can call this “engineering”). Basically the “triangle” that these three parameters specify, is the space that limits your colour volume and in practice there are only a few cases used, e.g. BR.601, BT.709, P3D65, or BT.2020.  People can of course get creative and put weird values in there, but I have not seen that at all happening.

Based on that, I would suggest rephrasing the note as follows:
> NOTE: The MasteringDisplayColourVolumeBox mdcv and ContentLightLevelBox clli have identical syntax to the SMPTE2086MasteringDisplayMetadataBox SmDm and ContentLightLevelBox CoLL, except that they are of type Box and not FullBox. However, the semantics of the MasteringDisplayColourVolumeBox and SMPTE2086MasteringDisplayMetadataBox have important differences and should not be confused.

OK?

**Comment by fcartegnie** [comment]
> OK?
ok

**Comment by kodabb** [comment]
@jamrial to my knowledge `mdcv` is only defined for qtff, not isobmff

otoh i agree with @fcartegnie that having two boxes for the same content is going to trigger a never ending list of bugs. I don't think rephrasing the note as suggested by @cconcolato is sufficient, but i don't have any other proposal that wouldn't be quite invasive at this point

**Comment by dwsinger** [comment]
@kodabb mdcv and clli are on their way towards standardization for isobmff at ISO
