### ISSUE TITLE
Links to av1 bitstream spec is error prone

### ISSUE THREAD

**Issue by kqyang** [AOMediaCodec/av1-isobmff#93]
For example, this is the link used for Sequence Header OBU: http://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=41.

It will point to an incorrect page when av1-spec is updated. 

Possible fixes:

(1) Use named links instead of page numbers. Not sure if pdf supports named links. If not, does av1-spec has a html version?

(2) Use versioned av1 spec, e.g. v1.0.0 (https://github.com/AOMediaCodec/av1-spec/releases/download/v1.0.0/av1-spec-v1.0.0.pdf), instead of using the latest spec at http://aomediacodec.github.io/av1-spec/av1-spec.pdf.

**Comment by tomfinegan** [comment]
Is there a link that's incorrect? (would be nice to correct any issues now)

> (1) Use named links instead of page numbers. Not sure if pdf supports named links. If not, does av1-spec has a html version?

No, and none that I know of at present. It's kind of a moot point-- the HTML versions of the spec that have existed thus far have not have the necessary anchors for link targets. Page numbers have actually been the more accurate link in practice.

> (2) Use versioned av1 spec, e.g. v1.0.0 (https://github.com/AOMediaCodec/av1-spec/releases/download/v1.0.0/av1-spec-v1.0.0.pdf), instead of using the latest spec at http://aomediacodec.github.io/av1-spec/av1-spec.pdf.

This is worse than what we have at present. You can't link to a page at all when you use the v1.0.0 link-- it's direct download, and opening the downloaded copy sheds the anchor.

**Comment by kqyang** [comment]
> Page numbers have actually been the more accurate link in practice.

It is only accurate when the paragraph is written. Will break any time in the future. 

There are more problems, e.g. when the av1 bitstream spec is updated, we may need to update this spec (av1 in mp4) as the page numbers could be different even if the changes in av1 bitstream is  irrelevant.

> it's direct download, 

Can we fix it instead? For example, include a versioned spec along with the latest spec, maybe at http://aomediacodec.github.io/av1-spec/av1-spec-v1.0.0.pdf?

**Comment by kqyang** [comment]
> Is there a link that's incorrect? (would be nice to correct any issues now)

Yes. I checked a few links. There are already some links broken. Not sure if it is due to changes in the bit stream spec or if it has problems since the beginning.

For example:

- Metadata OBUs is at page 46 not page 47. The correct link is https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=46.

- Tile group OBU is at page 71 not page 72. The correct link is https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=71.

**Comment by cconcolato** [comment]
closed per #94
